// Contract tests: postcard.ts and the BLE UUIDs must match the firmware
// release pinned in package.json ("corisco.firmware"). The vectors come from
// `npm run fetch-vectors` (.contract/vectors.json), generated by the
// firmware repo's corisco-protocol crate from the real Rust types.
import { existsSync, readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  REQUEST_CHARACTERISTIC_UUID,
  RESPONSE_CHARACTERISTIC_UUID,
  SERVICE_UUID,
} from "../src/ble-uuids";
import { decodeResponse, encodeRequest, type Request, type Response } from "../src/postcard";

type Case = { name: string; value: unknown; hex: string };
type Vectors = {
  protocol: number;
  uuids: { service: string; request: string; response: string };
  requests: Case[];
  responses: Case[];
};

const pin = JSON.parse(readFileSync("package.json", "utf8")).corisco.firmware as {
  tag: string;
  protocol: number;
};

if (!existsSync(".contract/vectors.json")) {
  throw new Error("Missing .contract/vectors.json -- run `npm run fetch-vectors` first.");
}
const vectors: Vectors = JSON.parse(readFileSync(".contract/vectors.json", "utf8"));

const hex = (b: Uint8Array) => Buffer.from(b).toString("hex");
const unhex = (h: string) => new Uint8Array(Buffer.from(h, "hex"));
const camel = (s: string) => s.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase());

// serde JSON -> the app's types. Rust `Vec<u8>` is a JSON number array, a
// unit enum variant is a bare string, a data variant is `{Name: {...}}`,
// and `None` is null. `amount_sats` is a u64, which the app models as bigint.
const LISTS_OF_OBJECTS = new Set(["statechain_commitments", "shares", "proofs"]);
function convert(key: string, v: unknown): unknown {
  if (v === null) return undefined;
  if (key === "amount_sats") return BigInt(v as number);
  if (Array.isArray(v)) {
    if (LISTS_OF_OBJECTS.has(key)) {
      return v.map((x) => (Array.isArray(x) ? new Uint8Array(x) : convertFields(x as object)));
    }
    return new Uint8Array(v as number[]);
  }
  if (typeof v === "object") return convertFields(v as object);
  return v;
}
function convertFields(o: object): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(o)) out[camel(k)] = convert(k, v);
  return out;
}
// Externally tagged enum -> `{ type, ...fields }`.
function convertEnum(v: unknown): Record<string, unknown> {
  if (typeof v === "string") return { type: v };
  const [[name, fields]] = Object.entries(v as object);
  return { type: name, ...convertFields(fields as object) };
}
const KEY_DERIVATION_FIELDS = ["first", "second"];
function toRequest(v: unknown): Request {
  const e = convertEnum(v);
  for (const f of KEY_DERIVATION_FIELDS) {
    if (typeof (v as any)?.[e.type as string]?.[f] !== "undefined") {
      e[f] = convertEnum((v as any)[e.type as string][f]);
    }
  }
  return e as Request;
}

describe(`firmware ${pin.tag} (protocol ${pin.protocol})`, () => {
  it("pinned protocol number matches the release's vectors", () => {
    expect(vectors.protocol).toBe(pin.protocol);
  });

  it("GATT UUIDs match", () => {
    expect({
      service: SERVICE_UUID,
      request: REQUEST_CHARACTERISTIC_UUID,
      response: RESPONSE_CHARACTERISTIC_UUID,
    }).toEqual(vectors.uuids);
  });

  describe("encodeRequest produces the firmware's bytes", () => {
    for (const c of vectors.requests) {
      it(c.name, () => {
        expect(hex(encodeRequest(toRequest(c.value)))).toBe(c.hex);
      });
    }
  });

  describe("decodeResponse reads the firmware's bytes", () => {
    for (const c of vectors.responses) {
      it(c.name, () => {
        expect(decodeResponse(unhex(c.hex))).toEqual(convertEnum(c.value) as Response);
      });
    }
  });
});
